/**
 * D2 decision 10: Foundry Functions use a generated copy of packages/domain/src, never a hand-copied one.
 * This module decides what the copy must contain. `npm run domain:sync` writes it, and
 * scripts/domain-copy.test.ts fails when the copy in clearspend-functions differs from it.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT } from "./paths.js";

export const DOMAIN_SOURCE_DIR = join(REPO_ROOT, "packages", "domain", "src");

/** The clone of the Foundry repository `clearspend-functions`. Override with CLEARSPEND_FUNCTIONS_DIR. */
export const FUNCTIONS_REPO_DIR = process.env.CLEARSPEND_FUNCTIONS_DIR ?? join(REPO_ROOT, "..", "clearspend-functions");

/** Not `src/generated/`: the template's .gitignore excludes that path, so Foundry would never receive the copy. */
export const DOMAIN_TARGET_DIR = join(FUNCTIONS_REPO_DIR, "typescript-functions", "src", "domain");

export const MANIFEST_FILE = "SOURCE.json";
/** A generated constant that each CsCostSnapshot records as `rulesVersion` (I1: which rules made the numbers). */
export const RULES_VERSION_FILE = "rulesVersion.ts";

export interface DomainManifest {
  readonly generatedBy: string;
  readonly sourceDir: string;
  /** SHA-256 of each source file, by file name. */
  readonly files: Readonly<Record<string, string>>;
}

export const sha256 = (text: string): string => createHash("sha256").update(text, "utf-8").digest("hex");

/** The domain source files: every .ts file except tests. Test fixtures are in a subfolder and are not copied. */
export function domainSourceFiles(): string[] {
  return readdirSync(DOMAIN_SOURCE_DIR, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts") && !entry.name.endsWith(".test.ts"))
    .map((entry) => entry.name)
    .sort();
}

export function header(fileName: string): string {
  return (
    `// GENERATED from clearspend packages/domain/src/${fileName} by \`npm run domain:sync\`.\n` +
    "// Do not edit this copy. Change the source in clearspend, then sync again (D2 decision 10).\n\n"
  );
}

/** The exact files that the target folder must hold, by file name. */
export function expectedCopy(): Map<string, string> {
  const files = new Map<string, string>();
  const digests: Record<string, string> = {};
  for (const name of domainSourceFiles()) {
    const source = readFileSync(join(DOMAIN_SOURCE_DIR, name), "utf-8");
    files.set(name, header(name) + source);
    digests[name] = sha256(source);
  }
  const manifest: DomainManifest = {
    generatedBy: "clearspend npm run domain:sync",
    sourceDir: "packages/domain/src",
    files: digests,
  };
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  files.set(MANIFEST_FILE, manifestText);
  files.set(
    RULES_VERSION_FILE,
    "// GENERATED from the SOURCE.json manifest by `npm run domain:sync`. Do not edit this file.\n\n" +
      "/** SHA-256 of SOURCE.json: it changes whenever any rule in packages/domain changes. */\n" +
      `export const RULES_VERSION = "domain-sha256:${sha256(manifestText).slice(0, 16)}";\n`,
  );
  return files;
}
